sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t kevincoakley/asterixdb .

script:
    - docker run --name my_asterixdb -d -p 127.0.0.1:19001:19001 kevincoakley/asterixdb
    - sleep 60
    - bash ./tests/test_port_19001.sh

after_script:
    - docker ps -a
    - docker logs my_asterixdb
    - docker top my_asterixdb
