sudo: required

services:
    - docker

before_install:
    - docker info
    - docker version
    - docker build -t kevincoakley/astrixdb .
    - docker run --name my_astrixdb -d -p 19001:19001 kevincoakley/astrixdb
    - docker ps -a

script:
    - HTTP_STATUS=`curl -sI http://127.0.0.1:19001/ | grep HTTP`; if [[ $HTTP_STATUS == *"200 OK"* ]]; then exit 0; else exit 1; fi
